SELECT O.id, C.NOMBRES, C.APELLIDOS, C.DIRECCION,P.DESCRIPCION,P.PRECIO, O.MONTO_TOTAL,O.CANTIDAD,CODIGO  
from CLIENTE, producto,cat_estado C INNER join ORDEN O on C.ID=O.CLIENTE_ID
INNER JOIN ORDEN O on PRODUCTO P WHERE P.ID=O.PRODUCTO_ID
INNER join ORDEN O on CAT_ESTADO CAT WHERE CAT.ID=O.CAT_ESTADO_ID
where MONTO_TOTAL>=1000.00

SELECT * FROM ORDEN, CLIENTE WHERE CLIENTE_ID=ID

SELECT * FROM ORDEN INNER JOIN CLIENTE ON CLIENTE_ID=ID

 select C.NOMBRES, APELLIDOS, DIRECCION
  from CLIENTE C
  join ORDEN O
  on C.ID=O.CLIENTE_ID;
   select O.id, p.DESCRIPCION,p.PRECIO, O.MONTO_TOTAL,O.CANTIDAD
  from PRODUCTO p
  INNER join ORDEN O
  on p.ID=O.PRODUCTO_ID;
  select O.id, O.MONTO_TOTAL,O.CANTIDAD,CAT.CODIGO
  from CAT_ESTADO CAT
  INNER join ORDEN O
  on CAT.ID=O.CAT_ESTADO_ID where MONTO_TOTAL>=1000.00;
SELECT 
    ID,
   NOMBRES, APELLIDOS, DIRECCION,
   DESCRIPCION,P.PRECIO, O.MONTO_TOTAL,O.CANTIDAD,CODIGO  AS supplier
FROM
    products
INNER JOIN
    categories ON categories.categoryID = products.categoryID
INNER JOIN
    suppliers ON suppliers.supplierID = products.supplierID